name: Production Docker CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

  ECR_REPOSITORY_URL: ${{ vars.ECR_REPOSITORY_URL }}

jobs:
  build-and-test:
    name: Build Docker Image & Run Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Prepare Python environment for pytest
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install test dependencies
      - name: Install Test Dependencies
        run: pip install -r app/requirements-dev.txt

      # 4. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Build Docker images
      - name: Build Docker Compose Images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker compose down -v
          docker compose build

      # 6. Start containers
      - name: Start Docker Compose
        run: docker compose up -d

      # 7. Run integration tests
      - name: Run Integration Tests
        run: |
          pytest -v tests/

      # 8. Show logs if test/build fails
      - name: Print Container Logs on Failure
        if: failure()
        run: docker compose logs

      - name: Debug OIDC Claims
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com')
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            )
            console.log("aud:", payload.aud)
            console.log("sub:", payload.sub)
            console.log("ref:", payload.ref)
            console.log("repository:", payload.repository)
            console.log("repository_id:", payload.repository_id)
            console.log("repository_owner_id:", payload.repository_owner_id)

      # 9. Authenticate GitHub Actions with AWS
      # Only publish when code is actually pushed to master.
      # Pull requests only build + test.
      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::803872867747:role/ecr-permission
          aws-region: ${{ env.AWS_REGION }}

      # 10. Login Docker to ECR
      - name: Login to Amazon ECR
        if: github.ref == 'refs/heads/master'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 11. Tag the SAME tested image with Git commit SHA and push to ECR
      - name: Tag and Push Image to ECR
        if: github.ref == 'refs/heads/master'
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag multi-container-web:latest \
            $ECR_REPOSITORY_URL:$IMAGE_TAG

          docker push \
            $ECR_REPOSITORY_URL:$IMAGE_TAG

      # 12. Cleanup CI containers
      - name: Cleanup Docker Compose
        if: always()
        run: docker compose down -v


### CD
  deploy:
    name: Deploy to EC2
    needs: build-and-test

    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    env:

      EC2_INSTANCE_1: ${{ vars.EC2_INSTANCE_1 }}
      EC2_INSTANCE_2: ${{ vars.EC2_INSTANCE_2 }}

      # Same SHA that CI pushed to ECR
      IMAGE_TAG: ${{ github.sha }}

    steps:

      # =====================================================
      # 1. Authenticate GitHub Actions to AWS using OIDC
      # =====================================================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # =====================================================
      # 2. Deploy EC2 #1
      # =====================================================
      - name: Deploy EC2 #1
        id: deploy_ec2_1
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_1" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy $IMAGE_TAG to EC2 #1" \
            --parameters commands="[
              \"cd /opt/myproject\",
              \"aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY\",
              \"sed -i 's|^ECR_IMAGE=.*|ECR_IMAGE=$ECR_REPOSITORY_URL:$IMAGE_TAG|' .env\",
              \"docker compose pull\",
              \"docker compose up -d\",
              \"sleep 10\",
              \"curl -f http://localhost:8000\"
            ]" \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID" >> "$GITHUB_OUTPUT"

      # =====================================================
      # 3. Wait for EC2 #1 and verify deployment
      # =====================================================
      - name: Verify EC2 #1
        run: |
          aws ssm wait command-executed \
            --command-id "${{ steps.deploy_ec2_1.outputs.command_id }}" \
            --instance-id "$EC2_INSTANCE_1"

          aws ssm get-command-invocation \
            --command-id "${{ steps.deploy_ec2_1.outputs.command_id }}" \
            --instance-id "$EC2_INSTANCE_1"

      # =====================================================
      # 4. Deploy EC2 #2
      # =====================================================
      - name: Deploy EC2 #2
        id: deploy_ec2_2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_2" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy $IMAGE_TAG to EC2 #2" \
            --parameters commands="[
              \"cd /opt/myproject\",
              \"aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY\",
              \"sed -i 's|^ECR_IMAGE=.*|ECR_IMAGE=$ECR_REPOSITORY_URL:$IMAGE_TAG|' .env\",
              \"docker compose pull\",
              \"docker compose up -d\",
              \"sleep 10\",
              \"curl -f http://localhost:8000\"
            ]" \
            --query "Command.CommandId" \
            --output text)

          echo "command_id=$COMMAND_ID" >> "$GITHUB_OUTPUT"

      # =====================================================
      # 5. Wait for EC2 #2 and verify deployment
      # =====================================================
      - name: Verify EC2 #2
        run: |
          aws ssm wait command-executed \
            --command-id "${{ steps.deploy_ec2_2.outputs.command_id }}" \
            --instance-id "$EC2_INSTANCE_2"

          aws ssm get-command-invocation \
            --command-id "${{ steps.deploy_ec2_2.outputs.command_id }}" \
            --instance-id "$EC2_INSTANCE_2"

      # =====================================================
      # 6. Deployment result
      # =====================================================
      - name: Deployment Summary
        run: |
          echo "Deployment successful"
          echo "Image: $ECR_REPOSITORY_URL:$IMAGE_TAG"
          echo "EC2 #1: $EC2_INSTANCE_1"
          echo "EC2 #2: $EC2_INSTANCE_2"